#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🐶 - Hi, I'm Husky! Let me check everything is fine before commiting."
echo "🐶 - First, let me clean up your code..."
# Not fixed yet
#yarn lint-apply
echo "🐶 - Awesome! Now, let's run all tests..."
#yarn test
echo "🐶 - Horray! All tests passed!"
echo "🐶 - This commit looks cool 👌"
